---
title: "GBK, ECOV, MSE"
output: html_document
date: "2025-04-16"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, cache = TRUE)

# TO DO: COPY SOURCE CODE (SPECIFICALLY THE LOOP THROUGH OM FXN) AND USE BROWSER() TO STEP THROUGH WHAT'S GIVING TROUBLE

# library(pak)
# library(devtools)
# pak::pkg_install("timjmiller/wham")
# devtools::install_github("lichengxue/whamMSE", dependencies=TRUE)
# devtools::install_github("NOAA-EDAB/ecodata", dependencies=TRUE, build = FALSE)

library(wham)
library(whamMSE)
library(ecodata)
library(dplyr)

write.dir <- "C:/Users/swulfing/Documents/GitHub/UMassD/YT_proj"
setwd(write.dir)

gb_dat <- read_asap3_dat("ASAPfiles_5.14Pull/GBK.DAT")
input <- prepare_wham_input(gb_dat)

```

# READ ME
This is adapted from the attempt of 04.16 with Cheng Li's single stock MSE and TJ Miller's WHAM without ASAP modules. I am now combining with Alex Hansell's GOM stock assessment to get an accurate assessment with ecov.

Next Steps:

- diagnose model issues (see Sarah email)

- Run MSE

- Contact Cheng for new features (esp. ecov)

```{r genBasicInfo}

year_start  <- 1  # starting year in the burn-in period
year_end    <- 20  # end year in the burn-in period
MSE_years   <- 3     # number of years in the feedback loop
# Note: no need to include MSE_years in simulation-estimation 

info <- generate_basic_info(n_stocks = input$data$n_stocks,
                            n_regions = input$data$n_regions,
                            n_indices = input$data$n_indices,
                            n_fleets = input$data$n_fleets,
                            n_seasons = input$data$n_seasons,
                            base.years = year_start:year_end,
                            n_feedback_years = MSE_years,
                            life_history = "medium", # Not sure if we're keeping this
                            n_ages = input$data$n_ages) 

# IF something is specifying age comp (which I'm not bc from vig) This could create a conflict when comparing to em
```

```{r specifyInfo}

# FIX THIS CHUNK FIRST I THINK THAT WILL HELP ALL YOUR OTHER PROBS (but who even knows at this point lol)
# COMPARE DIMENSIONS OF OLD CATCH/INDEX/F INFO AND FORCE THOSE ONTO THESE

###### OLD CODE ######

# 
# 
# # These right now are based on defaults or life history. FIND ARGUMENT TO PROVIDE MYSELF
basic_info = info$basic_info # collect basic information TRY input$data$catch_paa OR AGG CATCH
catch_info = info$catch_info # collect fleet catch information
index_info = info$index_info # collect survey information
F_info = info$F # collect fishing information

###### END ######
basic_info_FIX <- list(
    n_stocks = 1L,
    n_seasons = 1L,
    n_fleets = 1L,
    ages = 1:input$data$n_ages,
    n_fleets = input$data$n_fleets,
    fracyr_SSB = cbind(input$data$fracyr_SSB), #(n_years x n_stocks)
    maturity = input$data$mature, #(n_stocks x n_years x n_ages)
    years = as.integer(input$years), #(n_years)
    waa = input$data$waa, #(any no. x n_years x n_ages)
    waa_pointer_ssb = input$data$waa_pointer_ssb, #(n_stocks)
    spawn_regions = 1, #(n_stocks)
    spawn_seasons = 1 #(n_stocks)
)

basic_info$ages <-            basic_info_FIX$ages
basic_info$n_fleets <-        basic_info_FIX$n_fleets
basic_info$fracyr_SSB <-      basic_info_FIX$fracyr_SSB
basic_info$maturity <-        basic_info_FIX$maturity
basic_info$years <-           basic_info_FIX$years
basic_info$waa <-             basic_info_FIX$waa
basic_info$waa_pointer_ssb <- basic_info_FIX$waa_pointer_ssb
basic_info$waa_pointer_indices <- input[["data"]][["waa_pointer_indices"]]
basic_info$waa_pointer_M <- input$data$waa_pointer_M


catch_info_FIX <- list(
    n_fleets = NCOL(input$data$agg_catch), #(n_fleets)
    agg_catch = cbind(input$data$agg_catch), #(n_years x n_fleets)
    agg_catch_cv = cbind(sqrt(exp(input$data$agg_catch_sigma^2) - 1)), #(n_years x n_fleets)
    catch_paa = input$data$catch_paa, #(n_fleets x n_years x n_ages)
    use_catch_paa = cbind(input$data$use_catch_paa), #(n_years x n_fleets), 0: don't use, 1: use
    catch_Neff = cbind(input$data$catch_Neff), #(n_years x n_fleets)
    selblock_pointer_fleets = cbind(input$data$selblock_pointer_fleets), #(n_years x n_fleets)
    waa_pointer_fleets = input$data$waa_pointer_fleets, #(n_fleets)
    fleet_regions = rep(1,input$data$n_fleets) #(n_fleets)
)

catch_info$n_fleets <-      catch_info_FIX$n_fleets
catch_info$agg_catch <-     catch_info_FIX$agg_catch
catch_info$agg_catch_cv <-  catch_info_FIX$agg_catch_cv#[1] #NOTE: THIS DIMENSION IS CHANGED FROM THE OG INPUT
catch_info$catch_paa <-     catch_info_FIX$catch_paa
catch_info$use_catch_paa <- catch_info_FIX$use_catch_paa
catch_info$catch_Neff <-    catch_info_FIX$catch_Neff
catch_info$selblock_pointer_fleets <- catch_info_FIX$selblock_pointer_fleets
catch_info$fleet_regions <- catch_info_FIX$fleet_regions


index_info_FIX <- list(
    n_indices = NCOL(input$data$agg_indices),
    agg_indices = cbind(input$data$agg_indices), #(n_years x n_indices)
    units_indices = input$data$units_indices, #(n_indices) 1: biomass 2: numbers
    units_index_paa = input$data$units_index_paa, #(n_indices) 1: biomass 2: numbers
    agg_index_cv = cbind(sqrt(exp(input$data$agg_index_sigma^2) - 1)), #(n_years x n_indices)
    index_Neff = cbind(input$data$index_Neff), #(n_years x n_indices)
    fracyr_indices = cbind(input$data$fracyr_indices), #(n_years x n_indices)
    use_indices = cbind(input$data$use_indices), #(n_years x n_indices)
    use_index_paa = cbind(input$data$use_index_paa),  #(n_years x n_indices)
    index_paa = input$data$index_paa,  #(n_indices x n_years x n_ages)
    selblock_pointer_indices = cbind(input$data$selblock_pointer_indices), #(n_years x n_indices)
    waa_pointer_indices = input$data$waa_pointer_indices, #(n_indices)
    index_regions = rep(1,input$data$n_indices)) #(n_indices)


## This doesn't matter apparently
# index_info_FIX$index_Neff <- replace(index_info_FIX$index_Neff, index_info_FIX$index_Neff == -999, NA)

index_info$n_indices <-       index_info_FIX$n_indices
index_info$agg_indices <-     index_info_FIX$agg_indices
index_info$units_indices <-   index_info_FIX$units_indices
index_info$units_index_paa <- index_info_FIX$units_index_paa
index_info$agg_index_cv <-    index_info_FIX$agg_index_cv
index_info$index_Neff <-      index_info_FIX$index_Neff # NOTE: SOME ENTRIES -999, CHANGED TO NAS
index_info$fracyr_indices <-  index_info_FIX$fracyr_indices
index_info$use_indices <-     index_info_FIX$use_indices
index_info$use_index_paa <-   index_info_FIX$use_index_paa
index_info$index_paa <-       index_info_FIX$index_paa
index_info$index_regions <-   index_info_FIX$index_regions

#initial values for annual fully-selected fishing mortality
F_info_FIX <- list(F = matrix(0.3, length(basic_info$years), catch_info$n_fleets)) #(n_years x n_fleets)
# NOTE: DO WE WANT TO TAKE AVERAGE OF ALEX'S M'S? I DONT THINK THOSE ARE FISHING M'S BUT CHECK
F_info$F <- F_info_FIX$F
```

```{r configs}

n_stocks  <- as.integer(basic_info['n_stocks'])
n_regions <- as.integer(basic_info['n_regions'])
n_fleets  <- as.integer(basic_info['n_fleets'])
n_indices <- as.integer(basic_info['n_indices'])
n_ages    <- as.integer(basic_info['n_ages'])

# Selectivity Configuration - ALEX CODE
sel2=list(
  model=c("age-specific",
          "logistic","logistic","logistic"), 
  re = c("ar1_y","none","none","none"), #re = c("ar1_y","none","none","none"), use ar1 to est sel but later fixing all 
  initial_pars=list(
    c(0.1,0.25,0.5,1,1,1), # Commercial fleet
    c(2,0.3), # Spring NEFSC
    c(2,0.3), # Fall NEFSC
    c(2,0.3)), # DFO survey
  fix_pars = list(
    c(4:6), # Estimate param for each age
    c(NULL), # bc logistic, these only estimate 2 params so just want to fix first one
    c(NULL),
    c(NULL))
)

# CHENG SELECTIVITY
# fleet_pars <- c(5,1)
# index_pars <- c(2,1)
# sel <- list(model=rep("logistic",n_fleets+n_indices),
#             initial_pars=c(rep(list(fleet_pars),n_fleets),rep(list(index_pars),n_indices)))

# M Configuration
M <- list(model="constant",initial_means=array(c(0.57, 0.33, 0.26, 0.23, 0.22, 0.22), dim = c(n_stocks,n_regions,n_ages)))

sigma        <- "rec+1"
re_cor       <- "iid"
ini.opt      <- "equilibrium" 
sigma_vals   <-  array(0.5, dim = c(n_stocks, n_regions, n_ages)) # NAA sigma

# NAA config
NAA_re <- list(N1_model=rep(ini.opt,n_stocks),
               sigma=rep(sigma,n_stocks),
               cor=rep(re_cor,n_stocks),
               recruit_model = 3,  # rChanged from ALEX code
               sigma_vals = sigma_vals) # NAA_where must be specified in basic_info!
```

```{r generateWHAM_noEcov}
input_NoEcov <- prepare_wham_input(basic_info = basic_info, 
                            selectivity = sel2, 
                            M = M, 
                            NAA_re = NAA_re,
                            catch_info = catch_info, 
                            index_info = index_info, 
                            F = F_info,
                            age_comp = "logistic-normal-pool0") 

# input_NoEcov[["data"]][["index_Neff"]] # Should I be making these NAs or 0?
# input_NoEcov[["data"]][["Ecov_obs"]]

```

```{r GenerateOMandData_noEcov}


random = input_NoEcov$random # check what processes are random effects
input_NoEcov$random = NULL # so inner optimization won't change simulated RE

### USE THIS OM WHEN DIAGNOSING ISSUES ###
# om <- fit_wham(input_NoEcov, do.fit = T, do.brps = T, MakeADFun.silent = TRUE,
#                do.retro = TRUE, do.osa = FALSE) #Changing do.retro and do.osa as per SGaichas email

### END ###

om <- fit_wham(input, do.fit = F, do.brps = T, MakeADFun.silent = TRUE)
# Note: do.fit must be FALSE (no modeling fitting yet)


# plot_wham_output(om)

###### DOING THIS CAUSES NAS TO BE PRODUCED ######
# input_NoEcov$par$mean_rec_pars[,1]<-c(mean(om$rep$log_SR_a)) # TOOK OUT SUBSCRIPTS FROM OG CODE
# input_NoEcov$par$mean_rec_pars[,2]<-c(mean(om$rep$log_SR_b))
# 
# om_fix <- fit_wham(input_NoEcov, do.fit = T, do.brps = T, MakeADFun.silent = TRUE, do.retro = FALSE, do.osa = FALSE)
# 
# check_convergence(om_fix)
######      ######

# input_NoEcov$par <- om$parList
# om_improve <- fit_wham(input_NoEcov, do.fit = T, do.brps = T, MakeADFun.silent = TRUE,
#                do.retro = TRUE, do.osa = FALSE)
# 
om_with_data <- update_om_fn(om, seed = 123, random = random)






### END
assess.interval <- 3 # Note: assessment interval is 3 years, given the feedback period is 3 years, there will be only 1 assessment
base.years      <- year_start:year_end # Burn-in period
first.year      <- head(base.years,1)
terminal.year   <- tail(base.years,1)
assess.years    <- seq(terminal.year, tail(om$years,1)-assess.interval,by = assess.interval)

```

```{r om_issues, eval = FALSE}
# check_convergence(om)
# plot_wham_output(om)

# sim_fn <- function(om, self.fit = FALSE) {
#   input <- om$input
#   input$data <- om$simulate(complete = TRUE)
#   if (self.fit) {
#     fit <- fit_wham(input, do.osa = FALSE, do.retro = FALSE, MakeADFun.silent = TRUE)
#     return(fit)
#   } else return(input)
# }
# 
# set.seed(12345)
# self_sim_fit <- sim_fn(om, self.fit = TRUE)
# 
# check_convergence(self_sim_fit)

```

```{r MSE_noEcov, eval = FALSE}

mod = loop_through_fn_TEST(om = om_with_data,
                      em_info = info, 
                      random = random,
                      M_em = M, 
                      sel_em = sel2,
                      NAA_re_em = NAA_re, 
                      age_comp_em = "multinomial",
                      em.opt = list(separate.em = FALSE, 
                                    separate.em.type = 3, 
                                    do.move = FALSE, 
                                    est.move = FALSE),
                      assess_years = assess.years, 
                      assess_interval = assess.interval, 
                      base_years = base.years,
                      year.use = 20,
                      add.years = TRUE, 
                      # add.years=TRUE: assessment will use 20 years of data from historical period + new years in the feedback period
                      seed = 123,
                      save.sdrep = TRUE,
                      save.last.em = TRUE,
                      do.retro = TRUE, # Perform retrospective analysis
                      do.osa = TRUE) # Perform OSA residual analysis

```



