---
title: "YT_whamMSE"
output: html_document
date: "2025-03-28"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, cache = TRUE)

# library(pak)
# pak::pkg_install("timjmiller/wham")
# #devtools::install_github("timjmiller/wham", dependencies=TRUE)
# devtools::install_github("lichengxue/whamMSE", dependencies=TRUE)

library(wham)
library(whamMSE)

write.dir <- "C:/Users/swulfing/OneDrive - University of Massachusetts Dartmouth/Documents/GitHub/UMassD/YT_proj"
setwd(write.dir)

# Read in data files

# TO DO: ASK WHAT EACH OF THESE ARE (TWO GOM STOCKS, TWO SNE (but one doesn't work so idk))
# FIGURE OUT HOW TO PULL THESE YOURSELF. OR WAIT TILL DATA COMES OUT (see Jessie email) 

CCGOM <- read_asap3_dat("ASAP Dat files/CCGOM.DAT")
CCGOM <- read_asap3_dat("C:/Users/chengxue.li/Desktop/Sophie/CCGOM.DAT")
# CCGOM_alt3 <- read_asap3_dat("ASAP Dat files/CCGOM_alt3.DAT")
# GBK <- read_asap3_dat("ASAP Dat files/GBK.DAT")
# # SNE_2023 <- read_asap3_dat("ASAP Dat files/sne_asap_2023_RT.DAT") this one doesnt work. WHY? Accordign to Jessie this is the right one so figure it out
# SNEMA<- read_asap3_dat("ASAP Dat files/SNEMA_split.DAT")
```

```{r generateBasicInfo, eval = FALSE}

# THIS IS JUST TO COMPARE WHAT THE INPUT FILES LOOK LIKE IN ASAP VS THE VIGNETTES WHERE THEY GENERATE ON THEIR OWN

year_start  <- 1  # starting year in the burn-in period
year_end    <- 20  # end year in the burn-in period
MSE_years   <- 0     # number of years in the feedback loop
# Note: no need to include MSE_years in simulation-estimation


#asap4 <- CCGOM
 info <- generate_basic_info(n_stocks = 1,
                           n_regions = 1,
                           n_indices = 6, # FROM ASAP. WILL REDUCE LATER BASED ON OUTPUTS 
                           n_fleets = 1, 
                           #n_seasons = 4, OMMITTING BECAUSE ASSUMING DEFAULT?.
                           base.years = year_start:year_end,
                           n_feedback_years = MSE_years,
                           life_history = "medium",
                           n_ages = 6, # 6 AGE CLASSES. 1-6 THEN 6+. In this ex, not enough data past 6 yrs
                           #Fbar_ages = 12,
                           #recruit_model = 2,
                            F_info = list(F.year1 = 0.2, Fhist = "constant", Fmax = 0.4, Fmin = 0.2, change_time = 0.5, user_F = NULL), # WILL BE ADJUSTED WITH FITTING ESTIMATES AFTER FITTING MODEL
                             catch_info = list(catch_cv = 0.1, catch_Neff = 100),
                             index_info = list(index_cv = 0.1, index_Neff = 100, fracyr_indices = 0.625, q = 0.2),
                             fracyr_spawn = 0.625,
                             fracyr_seasons = NULL,
                             #fleet_pointer = NULL,
                             #index_pointer = NULL,
                             user_waa = NULL, # WAIT FOR CHENG
                             user_maturity = NULL, # WAIT FOR CHENG. NEED MATRICES FROM WAA FROM ASAP
                             bias.correct.process = FALSE, # Below = Default. Assumes no movement, no bias correction
                             bias.correct.observation = FALSE,
                             bias.correct.BRPs = FALSE,
                             mig_type = 0,
                             XSPR_R_opt = 2,
                             move_dyn = 0, # natal homing is assumed
                             onto_move = 0,
                             onto_move_pars = NULL,
                             apply_re_trend = 0,
                             trend_re_rate = NULL,
                             apply_mu_trend = 0,
                             trend_mu_rate = NULL,
                             age_mu_devs = NULL)

 basic_info = info$basic_info
 catch_info = info$catch_info
 index_info = info$index_info
 F_info = info$F # collect fishing information. Estimated in fitted model

# # see more details using ?generate_basic_info
 

# NOTES FROM CHENG
# 3: If you want to know which information from ASAP will be used in wham, you may check the source code of prepare_wham_input(): 'https://github.com/timjmiller/wham/blob/devel/R/prepare_wham_input.R'
 
# 4: I can later send you a list that tells you which information you can 100% translate from ASAP to MSE, and which information you need to simplify, and which information MSE package doesn't support. 

```

```{r Configurations}

# # Bi-directional movement - ARE YOU EVEN GOING TO SPECIFY THIUS
# basic_info <- generate_NAA_where(basic_info = basic_info, move.type = 2)
# # Note: the default is "bidirectional" movement (e.g. stock 1 move to region 2 and stock 2 move to region 1)
# 
# move <- generate_move(basic_info = basic_info, move.type = 2, move.rate = c(0.3), move.re = "constant") # Note: default is move = 0.3 (constant) for stock1 and 0.1 (constant) for the other stocks

# Selectivity and Natural Mortality Config
n_stocks  <- as.integer(basic_info['n_stocks'])
n_regions <- as.integer(basic_info['n_regions'])
n_fleets  <- as.integer(basic_info['n_fleets'])
n_indices <- as.integer(basic_info['n_indices'])
n_ages    <- as.integer(basic_info['n_ages'])

# Selectivity Configuration TRY USING LOGISTIC. CAN YOU FIX THE SELECTIVITIES?
fleet_pars <- c(0, 0.025, 0.325, 0.9, 1, 1) # Using 1995-2022 ASK GAVIN
index_pars <- list(c(0.2, 0.775, 0.975, 1, 1, 1),c(0, 0.1, 0.8, 1, 1, 1),
                   c(0, 0.2, 0.85, 1, 1, 1),c(0.125, 0.7, 0.975, 1, 1, 1),
                   c(0.3, 0.875, 1, 1, 1, 1), c(0.075, 0.75, 1, 1, 1, 1))

sel <- list(model=rep("age-specific",n_fleets+n_indices),
            initial_pars=c(rep(list(fleet_pars),n_fleets),(index_pars)),
            fix_pars = c(rep(list(1:6), n_fleets + n_indices)))# Want to fix all pars

fleet_pars <- c(0, 0.025, 0.325, 1, 1, 1) # Using 1995-2022 ASK GAVIN
index_pars <- list(c(0.2, 0.775, 1, 1, 1, 1),c(0, 0.1, 0.8, 1, 1, 1),
                   c(0, 0.2, 1, 1, 1, 1),c(0.125, 0.7, 1, 1, 1, 1),
                   c(0.3, 0.875, 1, 1, 1, 1), c(0.075, 0.75, 1, 1, 1, 1))
# Fix pars for ages 5-6
sel <- list(model=rep("age-specific",n_fleets+n_indices),
            initial_pars=c(rep(list(fleet_pars),n_fleets),(index_pars)),
            fix_pars = c(rep(list(3:6), n_fleets + n_indices)))# Want to fix ages 5-6 pars

# View(sel)
# # HOW CHENG DID SELECTIVITY IN VIGS
# fleet_pars1 <- c(5,1)
# index_pars1 <- c(2,1)
# sel_EX <- list(model=rep("logistic",4+4),
#              initial_pars=c(rep(list(fleet_pars1),4),rep(list(index_pars1),2)))
# 
# View(sel_EX)
# OLD EXAMPLE
# SELLIST <- list(model=rep("age-specific",5),
#                                   re=rep("none",5),                                  initial_pars=list(c(0,0.025,0.325,0.9,1,1),c(0.2,0.775,0.975,1,1,1),c(0, 0.1, 0.8, 1, 1, 1),
#                                                     c(0, 0.2, 0.85, 1, 1, 1),c(0.125, 0.7, 0.975, 1, 1, 1)), #ORDER: FLEET1 THEN. INDEX 1. FIX THESE AND ADD SELECTIVITIES TO ALL MODELS I RUN
#                                   fix_pars=list(4:5,4,2:4,
#                                                 4:5,4))
# 

# M Configuration
M <- list(model="constant",initial_means=array(0.2, dim = c(n_stocks,n_regions,n_ages)))


# NAA Config - WILL CHANGE IN M2-4?
sigma        <- "rec+1"
re_cor       <- "iid"
ini.opt      <- "equilibrium" # option <- c("age-specific-fe", "equilibrium")
Rec_sig      <- 0.5 # (sigma for recruitment)
NAA_sig      <- 0.5 # (sigma for NAA) 

sigma_vals = array(NAA_sig, dim = c(n_stocks, n_regions, n_ages)) # n_stocks x n_regions x n_ages
sigma_vals[,,1] = Rec_sig

# Set initial NAA for each stock
log_N1    <- rep(10,n_stocks)
log_N1[1] <- log(exp(10)*2) # N1_stock1 is 2 times higher than N1_stock2
N1_pars   <- generate_ini_N1(log_N1,basic_info,ini.opt)

# Set mean recruitment para. for each stock
mean_rec_par <- list()
for (i in 1:n_stocks) mean_rec_par[[i]] <- exp(log_N1[i])

NAA_re <- list(N1_model=rep(ini.opt,n_stocks),
               sigma=rep(sigma,n_stocks),
               cor=rep(re_cor,n_stocks),
               recruit_model = 2,  # rec random around the mean
               recruit_pars = mean_rec_par, 
               sigma_vals = sigma_vals,  
               N1_pars = N1_pars)
```

```{r WHAMonGBStock}

# Note: Selectivities taken from 2024 research track assessment doc CCGOM_Model_Runs.zip
# Number of selectivity blocks; asap4[[1]]$dat$use_index gives 4 n_indices. 4 + 1 (number of selectivity models i.e. fleets) = 5

# GAVIN QUESTION: IM USING SELECTIVITIES FROM 1995-2022. SHOULD I JUST USE THE MOST RECENT OR AVERAGE ACROSS YEARS? Cheng is currently developing code that can handle a gearshift usage

input <- prepare_wham_input(basic_info = basic_info, 
                            selectivity = sel, 
                            M = M, 
                            NAA_re = NAA_re, 
                            #move = move, WE'RE ASSUMING NO MOVEMENT. CAN I JUST COMMENT THIS OUT?
                            catch_info = catch_info, 
                            index_info = index_info, 
                            F = F_info)


om1 <- fit_wham(input, do.fit = F, do.brps = T, MakeADFun.silent = TRUE)
# Note: do.fit must be FALSE (no modeling fitting yet)
# # Fit model then check convergence
# m1 <- fit_wham(input, do.osa = F) # turn off OSA residuals to save time in ex
# check_convergence(om1) # Has converged. party.

```

```{r SelfTest}

sim_fn <- function(om, self.fit = FALSE){
  input <- om$input
  input$data <- om$simulate(complete=TRUE)
  # $simulate() is a function to generate datasets given the parameters defined in the OM
  # Note: process error and observation error are both turned on when simulating datasets 
  # To turn them off, use basic_info$simulate_process_error = 0 and basic_info$simulate_observation_error = 0
  if(self.fit) {
    fit <- fit_wham(input, do.osa = FALSE, do.retro = FALSE, MakeADFun.silent = FALSE)
    return(fit)
  } else return(input) 
}
# Note: turn on do.osa to calculate one-step-ahead residuals
# Note: turn on do.retro to calculate retrospective bias
set.seed(123)
self_sim_fit <- sim_fn(om1, self.fit = TRUE)

```

```{r CheckConvergeMakeHTML}
check_convergence(self_sim_fit) # check the model convergence
plot_wham_output(self_sim_fit, out.type = "html")

# 10. Create a sub directory and saves .png files (optional)

# report.dir <- "report"
# if (file.exists(main.dir, report.dir)){
# } else {
#   dir.create(file.path(main.dir, report.dir))
# }
# plot_wham_output(self_sim_fit, dir.main = file.path(main.dir, report.dir),out.type = 'png')

```

```{r CrossTest}
# Change NAA Configs
# EM with different NAA configuration
sigma      <- "rec+1"
re_cor     <- "2dar1" # Misspecification here

ini.opt    <- "equilibrium"
NAA_re <- list(N1_model=rep(ini.opt,n_stocks),
               sigma=rep(sigma,n_stocks),
               cor=rep(re_cor,n_stocks),
               NAA_where = basic_info$NAA_where)
               
# Generate wham input
input <- prepare_wham_input(basic_info = basic_info, selectivity = sel, M = M, NAA_re = NAA_re, move = move,
                            catch_info = catch_info, index_info = index_info, F = F_info)

# Generate EM
em <- fit_wham(input, do.fit = F, do.brps = F, MakeADFun.silent = TRUE)


## Cross Test fxn
sim_fn2 <- function(om, em, cross.fit = FALSE){
  input <- em$input
  input$data <- om$simulate(complete=TRUE)
  if(cross.fit) {
    fit <- fit_wham(input, do.osa = FALSE, do.retro = FALSE, MakeADFun.silent = FALSE)
    return(fit)
  } else return(input) 
}

set.seed(12345)
cross_sim_fit <- sim_fn2(om1, em, cross.fit = TRUE)

#Cek Convergence
check_convergence(cross_sim_fit)
```