---
title: "YT_whamMSE"
output: html_document
date: "2025-03-28"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, cache = TRUE)

# devtools::install_github("timjmiller/wham", dependencies=TRUE)
# devtools::install_github("lichengxue/wham-devel", dependencies=TRUE)

# devtools::install_github("lichengxue/whamMSE", dependencies=TRUE)
# Having a save issue. What happens when I do this

library(wham) #, lib.loc = "C:/Users/chengxue.li/AppData/Local/R/win-library/4.4/wham_Tim/")
library(whamMSE)

write.dir <- "C:/Users/swulfing/OneDrive - University of Massachusetts Dartmouth/Documents/GitHub/UMassD/YT_proj"
setwd(write.dir)

# Read in data files
# TO DO: ASK WHAT EACH OF THESE ARE (TWO GOM STOCKS, TWO SNE (but one doesn't work so idk))
# FIGURE OUT HOW TO PULL THESE YOURSELF. OR WAIT TILL DATA COMES OUT (see Jessie email) 
CCGOM <- read_asap3_dat("ASAP Dat files/CCGOM.DAT")
# CCGOM_alt3 <- read_asap3_dat("ASAP Dat files/CCGOM_alt3.DAT")
# GBK <- read_asap3_dat("ASAP Dat files/GBK.DAT")
# # SNE_2023 <- read_asap3_dat("ASAP Dat files/sne_asap_2023_RT.DAT") this one doesnt work. WHY? Accordign to Jessie this is the right one so figure it out
# SNEMA<- read_asap3_dat("ASAP Dat files/SNEMA_split.DAT")
```

```{r generateBasicInfo, eval = FALSE}

# THIS IS JUST TO COMPARE WHAT THE INPUT FILES LOOK LIKE IN ASAP VS THE VIGNETTES WHERE THEY GENERATE ON THEIR OWN

year_start  <- 1  # starting year in the burn-in period
year_end    <- 20  # end year in the burn-in period
MSE_years   <- 0     # number of years in the feedback loop
# Note: no need to include MSE_years in simulation-estimation


asap4 <- CCGOM
 info <- generate_basic_info(n_stocks = 1,
                           n_regions = 1,
                           n_indices = 10, #CAN SPECIFY NUMBER YOU WANT TO USE. WILL REMOVE SOME SURVEYS. LATER YOU HAVE A FLAG IF YOU CAN REMOVE SOME OF THESE
                           n_fleets = 1, #CATCH DATA
                           #n_seasons = 4,
                           base.years = year_start:year_end,
                           n_feedback_years = MSE_years,
                           life_history = "medium",
                           n_ages = 6, # 6 AGE CLASSES. 1-6 THEN 6+. In this ex, not enough data past 6 yrs
                           #Fbar_ages = 12,
                           #recruit_model = 2,
                            F_info = list(F.year1 = 0.2, Fhist = "constant", Fmax = 0.4, Fmin = 0.2, change_time = 0.5, user_F = NULL), #historical fishing mortality (from fleet). Keep for now then adjust with fishing estimate after fitting the model
                             catch_info = list(catch_cv = 0.1, catch_Neff = 100),
                             index_info = list(index_cv = 0.1, index_Neff = 100, fracyr_indices = 0.625, q = 0.2),
                             fracyr_spawn = 0.625,
                             fracyr_seasons = NULL,
                             #fleet_pointer = NULL,
                             #index_pointer = NULL,
                             user_waa = NULL, #Look into WAA_mat from ASAP. May need two matrices for the MSE feedback period. Best to stabilize WAA by taking 3-5 yr average
                             user_maturity = NULL, #mat at age. People typically use 3-5 yr average. Look under asap4[[1]]$dat$maturity for mtx. Last year = last row. Need mtx with same dimension pasted at the bottom of this one.
                             bias.correct.process = FALSE, # Keep biases same. Below asumes no movement, no bias correction. Below is default. Could be deleted (we think)
                             bias.correct.observation = FALSE,
                             bias.correct.BRPs = FALSE,
                             mig_type = 0, #Everything below this is movement
                             XSPR_R_opt = 2,
                             move_dyn = 0, # natal homing is assumed
                             onto_move = 0,
                             onto_move_pars = NULL,
                             apply_re_trend = 0,
                             trend_re_rate = NULL,
                             apply_mu_trend = 0,
                             trend_mu_rate = NULL,
                             age_mu_devs = NULL)

 basic_info = info$basic_info # collect basic information
 catch_info = info$catch_info # collect fleet catch information. Subset focusing just on the catch itself. 
 index_info = info$index_info # collect survey information. Some indices will have agregate catch, some have more thorough info
 F_info = info$F # collect fishing information. Estimated in fitted model

# # see more details using ?generate_basic_info


#### CHENG: I THINK ONE OF MY BIGGEST HURDLES IS JUST THAT I'M USING AN ASAP FILE AS OPPOSED TO GENERATED DATA. BECAUSE OF THIS, THERE ARE PARTS THAT I'M FOLLOWING TJ MILLERS WHAM VIGNETTES (I CAN SEND THEM IF THAT'S HELPFUL). I'M STILL UNDERSTANDING ASAP FILES SO CAN HAVE A HARD TIME TRANSLATING BETWEEN THE GENERATED INFO IN THE VIGNETTE AND THE ASAP OUTPUT ####

# 1: You are not the only one having this trouble. The current MSE package requires users to simplify the ASAP Data. However, I can try to help you translate ASAP info as much as possible to whamMSE. 
 
# 2: The problem is an ASAP file has a lot of information (some will be used in wham some will never be used in wham!) which requires an R wrapper that can completely handle every type of information in detail for different stocks, which is difficult especially for a early stage of a MSE platform.  
 
# 3: If you want to know which information from ASAP will be used in wham, you may check the source code of prepare_wham_input(): 'https://github.com/timjmiller/wham/blob/devel/R/prepare_wham_input.R'
 
# 4: I can later send you a list that tells you which information you can 100% translate from ASAP to MSE, and which information you need to simplify, and which information MSE package doesn't support. 
 
####CHENG: ALSO IF I RUN THIS CODE AS IS, I GET AN ERROR:  "unused arguments (Fbar_ages = 12, recruit_model = 2, fleet_pointer = NULL, index_pointer = NULL)" IVE JUST BEEN COMMENTING THOSE ARGUMENTS OUT BUT I'M NOT SURE IF I SHOULD ####

## Reply: You are right, vignettes haven't been updated since Jan, which is completely my fault. I will try to update them this week and let you know when I'm done. 

```

```{r WHAMonGBStock}
# I'm just naming this asap 4 to compare to the example file

wham.dir <- find.package("wham")
file.copy(from=file.path(wham.dir,"extdata","ex1_SNEMAYT.dat"), to=write.dir, overwrite=FALSE)
asap3 <- read_asap3_dat("ex1_SNEMAYT.dat") #Just so I can compare to the example data

# recruitment model: random about mean, no S-R function (recruit_model = 2)
# recruitment deviations: independent random effects (NAA_re = list(sigma="rec", cor="iid"))
# selectivity: age-specific (fix sel=1 for ages 4-5 in fishery, age 4 in index1, and ages 2-4 in index2)

# input1 <- prepare_wham_input(asap4, recruit_model=2, model_name="Trying one stock: GOM Yellowtail Flounder",
#                               selectivity=list(model=rep("age-specific",11),
#                                   re=rep("none",11),
#                                   initial_pars=list(c(0.5,0.5,0.5,1,1,0.5),c(0.5,0.5,0.5,1,0.5,0.5),c(0.5,1,1,1,0.5,0.5),
#                                                     c(0.5,0.5,0.5,1,1,0.5),c(0.5,0.5,0.5,1,0.5,0.5),c(0.5,1,1,1,0.5,0.5),
#                                                     c(0.5,0.5,0.5,1,1,0.5),c(0.5,0.5,0.5,1,0.5,0.5),c(0.5,1,1,1,0.5,0.5),
#                                                     c(0.5,0.5,0.5,1,1,0.5),c(0.5,0.5,0.5,1,0.5,0.5)),
#                                   fix_pars=list(4:5,4,2:4,
#                                                 4:5,4,2:4,
#                                                 4:5,4,2:4,
#                                                 4:5,4)),
#                               NAA_re = list(sigma="rec", cor="iid")) # Including selectivity throws an error I haven't fixed yet

input1 <- prepare_wham_input(asap4, recruit_model=2, model_name="Trying one stock: GOM Yellowtail Flounder",
                              selectivity=list(model=rep("age-specific",5),
                                  re=rep("none",5),
                                  initial_pars=list(c(0.5,0.5,0.5,1,1,0.5),c(0.5,0.5,0.5,1,0.5,0.5),c(0.5,1,1,1,0.5,0.5),
                                                    c(0.5,0.5,0.5,1,1,0.5),c(0.5,0.5,0.5,1,0.5,0.5)), #ORDER: FLEET1 THEN. INDEX 1. FIX THESE AND ADD SELECTIVITIES TO ALL MODELS I RUN
                                  fix_pars=list(4:5,4,2:4,
                                                4:5,4)),
                              NAA_re = list(sigma="rec", cor="iid")) # Including selectivity throws an error I haven't 

# This code should work but please double check those initial sel values

# Fit model then check convergence
m1 <- fit_wham(input1, do.osa = F) # turn off OSA residuals to save time in ex
check_convergence(m1) # Has converged. party.

# # EXAMLE CODE
# input1 <- prepare_wham_input(asap3, recruit_model=2, model_name="Ex 1: SNEMA Yellowtail Flounder",
#                               selectivity=list(model=rep("age-specific",3), 
#                                   re=rep("none",3), 
#                                   initial_pars=list(c(0.5,0.5,0.5,1,1,0.5),c(0.5,0.5,0.5,1,0.5,0.5),c(0.5,1,1,1,0.5,0.5)),  
#                                   fix_pars=list(4:5,4,2:4)),
#                               NAA_re = list(sigma="rec", cor="iid"))


####CHENG: I HAVEN'T FIGURED OUT YET HOW TO INCORPORATE SELECTIVITY. THE ERROR I GET IS "Length of selectivity$model must equal number of selectivity blocks (e.g., asap3$n_fleet_sel_blocks + asap3$n_indices)"IN THE EXAMPLE FILE OF THE WHAM VIGNETTES, THIS IS 3. IN MY ASAP FILE, THIS NUMBER IS 11 SO i ATTEMPTED TO COPY THE EXAMPLE CODE (LINE 117) FROM THE VIGNETTE AND THEN CREATE THIS SELECTIVITY TABLE ON LINE 119 FOR MY STOCK BUT STILL GOT THE SAME ERROR#### 

# Reply: This is a great question, the reason is for this stock, there are 10 indices in the ASAP file, but not all of them are used. Please check this code: asap4[[1]]$dat$use_index which is a vector of 0/1, 0 indicates that index will not be used in the assessment model, and 1 indicates will be used. So for your stock it seems the n_indices should be 4. That said the number of selectivity models should be 1 (1 fleet) + 4 (4 indices) = 5.

```

```{r m2thru4}

input2 <- prepare_wham_input(asap4, recruit_model=2, model_name="Ex 1: SNEMA Yellowtail Flounder",
                              # selectivity=list(model=rep("age-specific",3), 
                              #     re=rep("none",3), 
                              #     initial_pars=list(c(0.5,0.5,0.5,1,1,0.5),c(0.5,0.5,0.5,1,0.5,0.5),c(0.5,1,1,1,0.5,0.5)), 
                              #     fix_pars=list(4:5,4,2:4)),
                              NAA_re = list(sigma="rec", cor="iid"),
                              age_comp = "logistic-normal-miss0")
m2 <- fit_wham(input2, do.osa = F) # turn off OSA residuals to save time in ex
check_convergence(m2) # Converged


input3 <- prepare_wham_input(asap4, recruit_model=2, model_name="Ex 1: SNEMA Yellowtail Flounder",
                              selectivity=list(model=rep("age-specific",3),
                                  re=rep("none",3),
                                  initial_pars=list(c(0.5,0.5,0.5,1,1,0.5),c(0.5,0.5,0.5,1,0.5,0.5),c(0.5,1,1,1,0.5,0.5)),
                                  fix_pars=list(4:5,4,2:4)),
                              NAA_re = list(sigma="rec+1", cor="iid"))
m3 <- fit_wham(input3, do.osa = F) # turn off OSA residuals to save time in ex
check_convergence(m3)


input4 <- prepare_wham_input(asap4, recruit_model=2, model_name="Ex 1: SNEMA Yellowtail Flounder",
                              # selectivity=list(model=rep("age-specific",3), 
                              #     re=rep("none",3), 
                              #     initial_pars=list(c(0.5,0.5,0.5,1,1,0.5),c(0.5,0.5,0.5,1,0.5,0.5),c(0.5,1,1,1,0.5,0.5)), 
                              #     fix_pars=list(4:5,4,2:4)),
                              NAA_re = list(sigma="rec+1", cor="iid"),
                              age_comp = "logistic-normal-miss0")
m4 <- fit_wham(input4, do.osa = F) # turn off OSA residuals to save time in ex

check_convergence(m4)

# All converged. yay!!
mods <- list(m1=m1, m2=m2, m3=m3, m4=m4)
save("mods", file="ex1_models.RData")

# Reply: I can see m1-m4 were all converged by checking with the check_convergence function, but if you look at the standard error for estimated parameters using plot_wham_output(m2, out.type = "html"), you will the parameter estimates are associated with tremendously high SE, meaning that those models should not be considered "converged". The reason is because you didn't configure selectivities, so the model estimated all selectivity parameters freely. This is not typically what we do because we want to assume (or in other words, "fix") the selectivity for at least age for each fleet and index to be 1 (means that age is "fully selected" by that fleet fishing gear or survey gear). By fixing some ages to be 1 for each fleet and survey, you will stablize your model estimation and increase the chance of truly converged.

# Tips for tweaking selectivities to achieve model convergence: you are start with fixing sel for some ages to be 1, and then perform modeling fitting, if the model is not converged, then check which sel parameters are not well estimated. IF that sel par is estimated close to 1, then just fix that age to be 1 and then refit the model. The convergence issue are typically related to selectivity configuration so you should expect you spend some time playing with those sel par fixing. Initial value are normally not a big deal, so you can leave them there, however, remember that whenever you fix a sel par for a age, the corresponding initial sel for that age must be 1. 

# Sometimes if you think the sel of 1 is at max age, you may use logistic for that fleet or index to reduce the number of parameters you estimate in the model (2 parameters for logistic curve vs. 6 parameters for age-specific sel curve.). This may help you achieve model convergence too.

```

```{r selfTest}

# This is from MSE paper
sim_fn <- function(m4, self.fit = FALSE){
  input <- m4$input
  input$data <- m4$simulate(complete=TRUE)
  # $simulate() is a function to generate datasets given the parameters defined in the OM
  # Note: process error and observation error are both turned on when simulating datasets 
  # To turn them off, use basic_info$simulate_process_error = 0 and basic_info$simulate_observation_error = 0
  if(self.fit) {
    fit <- fit_wham(input, do.osa = FALSE, do.retro = FALSE, MakeADFun.silent = FALSE)
    return(fit)
  } else return(input) 
}
# Note: turn on do.osa to calculate one-step-ahead residuals
# Note: turn on do.retro to calculate retrospective bias
set.seed(12345)
self_sim_fit <- sim_fn(m4, self.fit = TRUE)

# Cek convergence of simulation

check_convergence(self_sim_fit) # check the model convergence SIMULATED MODEL CONVERGED

```

```{r compareModels}

res <- compare_wham_models(mods, table.opts=list(fname="ex1_table", sort=TRUE))
res$best
m4_proj <- project_wham(model=m4)
```

```{r plotAndDiagnostics}

plot_wham_output(mod=m4_proj) # default is png
plot_wham_output(mod=m4_proj, out.type='html')
```

```{r PerformMSE}

random = input4$random # check what processes are random effects
input4$random = NULL # so inner optimization won't change simulated RE
m4 <- fit_wham(input4, do.fit = F, do.brps = T, MakeADFun.silent = TRUE)
# Note: do.fit must be FALSE (no modeling fitting yet)

# Generate daaset
m4_with_data <- update_om_fn(m4, seed = 123, random = random)

# Specify assessment interval and assessment year in feedback loop

assess.interval <- 3 # Note: assessment interval is 3 years, given the feedback period is 3 years, there will be only 1 assessment
base.years      <- 1:20 # Burn-in period
first.year      <- head(base.years,1)
terminal.year   <- tail(base.years,1)
assess.years    <- seq(terminal.year, tail(m4$years,1)-assess.interval,by = assess.interval)

mods <- list() # Create a list to save MSE outputs

####CHENG: I THINK I UNDERSTAND THAT YOU'RE SPECIFYING HOW OFTEN TO DO ASSESSMENTS, BUT DOES ANY OF THIS INFORMATION HAVE TO COINCIDE WITH INFO FROM YOUR ASAP FILE####

```

```{r EM1}

#Converged model becomes the operating model. Do we want to simulate replicates. Ask gavin if you want to do replicates. See #12 in Cheng's 1st vignettes.

#These are from the selectivity configuration which I'm still figuring out
fleet_pars <- c(5,1)
index_pars <- c(2,1)
n_ages <- 6 #This was from looking at data in asapfile

n_stocks = n_regions = n_fleets = n_indices = 1

sel_em <- list(model=rep("logistic",n_fleets+n_indices),
               initial_pars=c(rep(list(fleet_pars),n_fleets),rep(list(index_pars),n_indices)))

NAA_re_em <- list(N1_model="equilibrium",sigma="rec+1",cor="iid")

M_em <- list(model="constant",initial_means=array(0.2, dim = c(n_stocks,n_regions,n_ages)))

mods[[1]] = loop_through_fn(om = m4_with_data,
                            em_info = input4, # This needs to be generate_basic_info => WHAM => MSE 
                            random = random,
                            M_em = M_em, 
                            sel_em = sel_em, # Configurations of process error in assessment model given unknown observations and dynamics
                            NAA_re_em = NAA_re_em, 
                            move_em = NULL,
                            age_comp_em = "multinomial",
                            em.opt = list(separate.em = TRUE, separate.em.type = 1, 
                                          do.move = FALSE, est.move = FALSE),
                            assess_years = assess.years, 
                            assess_interval = assess.interval, 
                            base_years = base.years,
                            year.use = 20, # number of years of data you want to use in the assessment model
                            #hcr.type = 1, # unused argument 
                            seed = 123,
                            save.sdrep = FALSE, 
                            save.last.em = TRUE)



####CHENG: OK THIS IS WHERE MY ERRORS START. THE FIRST ERROR I GET IS "unused arguemnt; hcr.type = 1" SO I'VE COMMENTED IT OUT. AND OF COURSE NOW THAT I'M RUNNING THIS, I'M GETTING A NEW ERROR WHICH SAYS "Now conducting stock assessment for year 20 Error in rep(1, n_fleets) : invalid 'times' argument" WHEN LOOKING AT traceback(), I THINK IT HAPPENS IN make_aggregate_data BUT I HAVEN'T FIGURED OUT WHY YET####

####CHENG: LINES 233-238 WERE SOME MORE SELECTIVITY CONFIGURATION STUFF THAT I JUST COPIED AND PASTED IN THERE TO MAKE IT RUN. NOT SURE HOW I WOULD CHANGE THIS TO APPLY TO MY STOCK####

# Reply: So this function can not handle a fitted wham model which uses that input data directly from an ASAP file. We need to translate ASAP info to generate_basic_info before using this MSE function. I will help you with that which may takes a couple of days. Again, there are some parts of info we need to simplify.

```

```{r EM2}

n_stocks = n_regions = 1
n_fleets = n_indices = 2
sel_em <- list(model=rep("logistic",n_fleets+n_indices),
               initial_pars=c(rep(list(fleet_pars),n_fleets),rep(list(index_pars),n_indices)))

NAA_re_em <- list(N1_model="equilibrium",sigma="rec+1",cor="iid")

M_em <- list(model="constant",initial_means=array(0.2, dim = c(n_stocks,n_regions,n_ages)))

mods[[2]] = loop_through_fn(om = m4_with_data, 
                            em_info = input4, 
                            random = random,
                            M_em = M_em, 
                            sel_em = sel_em, 
                            NAA_re_em = NAA_re_em, 
                            move_em = NULL,
                            age_comp_em = "multinomial",
                            em.opt = list(separate.em = TRUE, separate.em.type = 2, 
                                          do.move = FALSE, est.move = FALSE),
                            assess_years = assess.years, 
                            assess_interval = assess.interval, 
                            base_years = base.years,
                            year.use = 20, # number of years of data you want to use in the assessment model
                            #hcr.type = 1, 
                            seed = 123,
                            save.sdrep = FALSE)

####CHENG: NOW I'M GETTING A DIFFERENT ERROR "Now conducting stock assessment for year 20 Error in filter_and_generate_em_info(em_info, fleet_regions, index_regions,  : argument "em.opt" is missing, with no default" EVEN THOUGH EM.OPT IS IN THE MSE CODE ABOVE####
```





























